#!/bin/zsh
# Copyright 2024 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

foreach i ($@) do
  mkdir -p $i
  daynum=${${i:t}#day}
  if [[ -d input ]]; then
    mkdir -p input/$daynum
    touch input/$daynum/input.actual.txt
    expectfile="input/$daynum/input.actual.expected"
    if [[ ! -f $expectfile ]]; then
      echo "part1: \npart2: " > $expectfile
    fi
  fi
  for f in input.actual.txt input.actual.expected ; do
    if [ ! -e $i/$f ]; then
      ln -s ../input/$daynum/$f $i/$f
    fi
  done
done
exec gsnd -q -dNOSAFER -I${0:h} -- ${0:h}/generate.ps $@
