# Copyright 2026 Trevor Stone
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

RUSTC = rustc --edition=2024

generate: generate.rs
	$(RUSTC) generate.rs

clean:
	rm generate
